# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c47b8e45f71edccc68b90367ad53656e9b41297e9ab21409704cc8d8903537111a41a9e48f1246ac4af5444b772ff7cdaf3c8536264ef1d0de83686d5d2967a3

test:
  secret_key_base: f826b90563fff0f749fdc3f0ed89547729466e404733d9ced92c60e1c96c64449e59935117094f73bb0727c642f82690d213f351567ed0033bafa498c0e984dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
